# fly.toml app configuration file generated for laynote-websocket on 2025-07-10T12:38:19+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'laynote-websocket'
primary_region = 'lhr'

[build]
  dockerfile = 'app/Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 4
